# Site settings
title: Radio Fireball
email: hello@radiofireball.com
description: > # this means to ignore newlines until "baseurl:"
  Sweden's premier hard rock and metal programme
url: "http://thomaswaern.se" # the base hostname & protocol for your site
baseurl: /radiofireball
twitter_username: radiofireball

# Build settings
markdown: kramdown
